-- UMKM Desa Masaran: initial schema
-- Password is intentionally managed by Supabase Auth (auth.users), never by public tables.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'umkm')),
  username text unique,
  login_email text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_has_username check (
    (role = 'admin' and username is not null and login_email is not null)
    or role = 'umkm'
  )
);

create unique index if not exists profiles_username_lower_key
  on public.profiles (lower(username))
  where username is not null;

create table if not exists public.umkm (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles (id) on delete restrict,
  slug text not null unique,
  nama text not null,
  pemilik text not null,
  rt text,
  rw text,
  dukuh text,
  dusun text,
  alamat_lengkap text,
  no_wa text not null,
  instagram text,
  tiktok text,
  facebook text,
  shopee text,
  tokopedia text,
  google_maps text,
  keunggulan1 text,
  keunggulan2 text,
  keunggulan3 text,
  keunggulan4 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint umkm_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.kategori (
  id bigint generated by default as identity primary key,
  nama text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists kategori_nama_lower_key
  on public.kategori (lower(nama));

create table if not exists public.umkm_kategori (
  umkm_id bigint not null references public.umkm (id) on delete cascade,
  kategori_id bigint not null references public.kategori (id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (umkm_id, kategori_id)
);

create table if not exists public.produk (
  id bigint generated by default as identity primary key,
  id_umkm bigint not null references public.umkm (id) on delete cascade,
  nama text not null,
  deskripsi text,
  harga numeric(12, 2) not null check (harga >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produk_id_umkm_idx on public.produk (id_umkm);

create table if not exists public.umkm_images (
  id bigint generated by default as identity primary key,
  umkm_id bigint not null references public.umkm (id) on delete cascade,
  slot text not null check (slot in ('logo', 'gambar_1', 'gambar_2', 'gambar_3')),
  storage_path text not null unique,
  alt_text text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (umkm_id, slot)
);

create table if not exists public.desa (
  id smallint primary key default 1 check (id = 1),
  alamat text,
  no_telepon text,
  email text,
  tentang text,
  google_maps text,
  facebook text,
  instagram text,
  tiktok text,
  youtube text,
  balai_desa_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.desa (id) values (1) on conflict (id) do nothing;

create table if not exists public.desa_images (
  id bigint generated by default as identity primary key,
  desa_id smallint not null default 1 references public.desa (id) on delete cascade,
  urutan smallint not null check (urutan between 1 and 6),
  storage_path text not null unique,
  deskripsi text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (desa_id, urutan)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.owns_umkm(target_umkm_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.umkm
    where id = target_umkm_id and user_id = auth.uid()
  );
$$;

create or replace function public.can_manage_umkm_storage(object_name text)
returns boolean
language sql
stable
security definer
set search_path = public, storage
as $$
  select public.is_admin() or exists (
    select 1
    from public.umkm
    where user_id = auth.uid()
      and (storage.foldername(object_name))[1] = 'umkm'
      and (storage.foldername(object_name))[2] = id::text
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.owns_umkm(bigint) to anon, authenticated;
grant execute on function public.can_manage_umkm_storage(text) to anon, authenticated;

create trigger profiles_set_updated_at before update on public.profiles
  for each row execute procedure public.set_updated_at();
create trigger umkm_set_updated_at before update on public.umkm
  for each row execute procedure public.set_updated_at();
create trigger kategori_set_updated_at before update on public.kategori
  for each row execute procedure public.set_updated_at();
create trigger produk_set_updated_at before update on public.produk
  for each row execute procedure public.set_updated_at();
create trigger umkm_images_set_updated_at before update on public.umkm_images
  for each row execute procedure public.set_updated_at();
create trigger desa_set_updated_at before update on public.desa
  for each row execute procedure public.set_updated_at();
create trigger desa_images_set_updated_at before update on public.desa_images
  for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.umkm enable row level security;
alter table public.kategori enable row level security;
alter table public.umkm_kategori enable row level security;
alter table public.produk enable row level security;
alter table public.umkm_images enable row level security;
alter table public.desa enable row level security;
alter table public.desa_images enable row level security;

create policy "Profiles can be read by their owner or an admin"
  on public.profiles for select
  using (id = auth.uid() or public.is_admin());

create policy "Public can read UMKM"
  on public.umkm for select using (true);
create policy "Admins manage every UMKM"
  on public.umkm for all
  using (public.is_admin()) with check (public.is_admin());
create policy "UMKM owner updates own profile"
  on public.umkm for update
  using (public.owns_umkm(id)) with check (user_id = auth.uid());

create policy "Public can read categories"
  on public.kategori for select using (true);
create policy "Admins manage categories"
  on public.kategori for all
  using (public.is_admin()) with check (public.is_admin());

create policy "Public can read UMKM categories"
  on public.umkm_kategori for select using (true);
create policy "Admins manage UMKM categories"
  on public.umkm_kategori for all
  using (public.is_admin()) with check (public.is_admin());
create policy "UMKM owner manages own categories"
  on public.umkm_kategori for all
  using (public.owns_umkm(umkm_id)) with check (public.owns_umkm(umkm_id));

create policy "Public can read products"
  on public.produk for select using (true);
create policy "Admins manage every product"
  on public.produk for all
  using (public.is_admin()) with check (public.is_admin());
create policy "UMKM owner manages own products"
  on public.produk for all
  using (public.owns_umkm(id_umkm)) with check (public.owns_umkm(id_umkm));

create policy "Public can read UMKM images"
  on public.umkm_images for select using (true);
create policy "Admins manage every UMKM image"
  on public.umkm_images for all
  using (public.is_admin()) with check (public.is_admin());
create policy "UMKM owner manages own images"
  on public.umkm_images for all
  using (public.owns_umkm(umkm_id)) with check (public.owns_umkm(umkm_id));

create policy "Public can read village information"
  on public.desa for select using (true);
create policy "Admins manage village information"
  on public.desa for all
  using (public.is_admin()) with check (public.is_admin());

create policy "Public can read village images"
  on public.desa_images for select using (true);
create policy "Admins manage village images"
  on public.desa_images for all
  using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'umkm-media',
  'umkm-media',
  true,
  2097152,
  array['image/jpeg', 'image/png']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create policy "Public can view UMKM media"
  on storage.objects for select
  using (bucket_id = 'umkm-media');
create policy "Admins and owners upload UMKM media"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'umkm-media'
    and public.can_manage_umkm_storage(name)
  );
create policy "Admins and owners update UMKM media"
  on storage.objects for update to authenticated
  using (bucket_id = 'umkm-media' and public.can_manage_umkm_storage(name))
  with check (bucket_id = 'umkm-media' and public.can_manage_umkm_storage(name));
create policy "Admins and owners delete UMKM media"
  on storage.objects for delete to authenticated
  using (bucket_id = 'umkm-media' and public.can_manage_umkm_storage(name));
